[2023-01-14T13:51:17.283+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: user_processing.create_table manual__2023-01-14T13:51:14.722829+00:00 [queued]>
[2023-01-14T13:51:17.317+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: user_processing.create_table manual__2023-01-14T13:51:14.722829+00:00 [queued]>
[2023-01-14T13:51:17.318+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-14T13:51:17.320+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2023-01-14T13:51:17.321+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-14T13:51:17.360+0000] {taskinstance.py:1304} INFO - Executing <Task(SqliteOperator): create_table> on 2023-01-14 13:51:14.722829+00:00
[2023-01-14T13:51:17.371+0000] {standard_task_runner.py:55} INFO - Started process 34360 to run task
[2023-01-14T13:51:17.379+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'create_table', 'manual__2023-01-14T13:51:14.722829+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpm_hjoxbc']
[2023-01-14T13:51:17.384+0000] {standard_task_runner.py:83} INFO - Job 27: Subtask create_table
[2023-01-14T13:51:17.522+0000] {task_command.py:389} INFO - Running <TaskInstance: user_processing.create_table manual__2023-01-14T13:51:14.722829+00:00 [running]> on host 35e95982c619
[2023-01-14T13:51:17.661+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2023-01-14T13:51:14.722829+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-14T13:51:14.722829+00:00
[2023-01-14T13:51:17.663+0000] {sql.py:253} INFO - Executing: 
            CREATE TABLE IF NOT EXISTS users (
              firstname TEXT NOT NULL,
              lastname TEXT NOT NULL,
              country TEXT NOT NULL,
              username TEXT NOT NULL,
              password TEXT NOT NULL,
              email TEXT NOT NULL PRIMARY KEY
            );
            
[2023-01-14T13:51:17.679+0000] {base.py:73} INFO - Using connection ID 'db_sqlite' for task execution.
[2023-01-14T13:51:18.155+0000] {base.py:73} INFO - Using connection ID 'db_sqlite' for task execution.
[2023-01-14T13:51:18.165+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 261, in execute
    return_last=self.return_last,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 331, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/sqlite/hooks/sqlite.py", line 38, in get_conn
    conn = sqlite3.connect(airflow_conn.host)
sqlite3.OperationalError: unable to open database file
[2023-01-14T13:51:18.226+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=user_processing, task_id=create_table, execution_date=20230114T135114, start_date=20230114T135117, end_date=20230114T135118
[2023-01-14T13:51:18.260+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 27 for task create_table (unable to open database file; 34360)
[2023-01-14T13:51:18.356+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-14T13:51:18.480+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
