[2023-01-14T14:32:25.842+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: user_processing.storing_user manual__2023-01-14T14:32:11.328846+00:00 [queued]>
[2023-01-14T14:32:25.857+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: user_processing.storing_user manual__2023-01-14T14:32:11.328846+00:00 [queued]>
[2023-01-14T14:32:25.858+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-14T14:32:25.860+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2023-01-14T14:32:25.861+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-14T14:32:25.886+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): storing_user> on 2023-01-14 14:32:11.328846+00:00
[2023-01-14T14:32:25.902+0000] {standard_task_runner.py:55} INFO - Started process 36617 to run task
[2023-01-14T14:32:25.910+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'storing_user', 'manual__2023-01-14T14:32:11.328846+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpr_oxmv4o']
[2023-01-14T14:32:25.914+0000] {standard_task_runner.py:83} INFO - Job 45: Subtask storing_user
[2023-01-14T14:32:26.005+0000] {task_command.py:389} INFO - Running <TaskInstance: user_processing.storing_user manual__2023-01-14T14:32:11.328846+00:00 [running]> on host 35e95982c619
[2023-01-14T14:32:26.103+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=storing_user
AIRFLOW_CTX_EXECUTION_DATE=2023-01-14T14:32:11.328846+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-14T14:32:11.328846+00:00
[2023-01-14T14:32:26.106+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-01-14T14:32:26.107+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo -e ".separator ","\n.import \tmp\\processed_user.csv users" | sqlite3 C:/Users/tawan/Desktop/Airflow-docker/***.db ']
[2023-01-14T14:32:26.128+0000] {subprocess.py:86} INFO - Output:
[2023-01-14T14:32:26.134+0000] {subprocess.py:93} INFO - Error: unable to open database "C:/Users/tawan/Desktop/Airflow-docker/***.db": unable to open database file
[2023-01-14T14:32:26.135+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-01-14T14:32:26.153+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-01-14T14:32:26.159+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=user_processing, task_id=storing_user, execution_date=20230114T143211, start_date=20230114T143225, end_date=20230114T143226
[2023-01-14T14:32:26.176+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 45 for task storing_user (Bash command failed. The command returned a non-zero exit code 1.; 36617)
[2023-01-14T14:32:26.202+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-14T14:32:26.225+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
