[2023-01-14T13:51:47.270+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: user_processing.create_table manual__2023-01-14T13:51:44.200723+00:00 [queued]>
[2023-01-14T13:51:47.301+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: user_processing.create_table manual__2023-01-14T13:51:44.200723+00:00 [queued]>
[2023-01-14T13:51:47.302+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-14T13:51:47.304+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2023-01-14T13:51:47.305+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-14T13:51:47.347+0000] {taskinstance.py:1304} INFO - Executing <Task(SqliteOperator): create_table> on 2023-01-14 13:51:44.200723+00:00
[2023-01-14T13:51:47.360+0000] {standard_task_runner.py:55} INFO - Started process 34387 to run task
[2023-01-14T13:51:47.376+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'create_table', 'manual__2023-01-14T13:51:44.200723+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmprkghxxuz']
[2023-01-14T13:51:47.382+0000] {standard_task_runner.py:83} INFO - Job 28: Subtask create_table
[2023-01-14T13:51:47.532+0000] {task_command.py:389} INFO - Running <TaskInstance: user_processing.create_table manual__2023-01-14T13:51:44.200723+00:00 [running]> on host 35e95982c619
[2023-01-14T13:51:47.675+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2023-01-14T13:51:44.200723+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-14T13:51:44.200723+00:00
[2023-01-14T13:51:47.679+0000] {sql.py:253} INFO - Executing: 
            CREATE TABLE IF NOT EXISTS users (
              firstname TEXT NOT NULL,
              lastname TEXT NOT NULL,
              country TEXT NOT NULL,
              username TEXT NOT NULL,
              password TEXT NOT NULL,
              email TEXT NOT NULL PRIMARY KEY
            );
            
[2023-01-14T13:51:47.697+0000] {base.py:73} INFO - Using connection ID 'db_sqlite' for task execution.
[2023-01-14T13:51:48.151+0000] {base.py:73} INFO - Using connection ID 'db_sqlite' for task execution.
[2023-01-14T13:51:48.154+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 261, in execute
    return_last=self.return_last,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 331, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/sqlite/hooks/sqlite.py", line 38, in get_conn
    conn = sqlite3.connect(airflow_conn.host)
sqlite3.OperationalError: unable to open database file
[2023-01-14T13:51:48.170+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=user_processing, task_id=create_table, execution_date=20230114T135144, start_date=20230114T135147, end_date=20230114T135148
[2023-01-14T13:51:48.196+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 28 for task create_table (unable to open database file; 34387)
[2023-01-14T13:51:48.222+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-14T13:51:48.292+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
